### ISSUE TITLE
ModuleNotFoundError:

### ISSUE THREAD

**Issue by jethornton** [bhowiebkr/LinuxCNC-Config-Editor#1]
ModuleNotFoundError: No module named 'PyQt5.QtWebEngineWidgets'

https://github.com/jethornton/simple-pyqt5-deb

**Comment by bhowiebkr** [comment]
You're missing PyQtWebEngine

See the installation section on the readme. Run `pip3 install -r requirements.txt` to install web engine and any future dependencies.
